### ISSUE TITLE
pac paportal upload errors

### ISSUE THREAD

**Issue by eugenevanstaden** [microsoft/powerplatform-vscode#492] opened 2023-03-30 02:16 UTC
Current version of pac cli cause issues with paportal upload. It fails repeatedly on uploading records with the following error:

ManifestAction: NOT_FOUND detected for entity:adx_contentsnippet id:3cc3637f-0148-ec11-8c62-00224811189e 2023-03-29 10:08:38.2861 | INF | bolt.cli.CommandProcessor :: EndExecutingVerb (Success: False, Execution Time(ms): 757) 2023-03-29 10:08:38.3330 | FTL | bolt.Session :: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.Object,System.Object]' to type 'System.IConvertible'.|EXCEPTION: System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.Object,System.Object]' to type 'System.IConvertible'.    at System.Convert.ToInt32(Object value, IFormatProvider provider)    at bolt.module.paportal.PAPortalCommon.<>c.<AddAttributeByType>b__3_0(Object x)    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)    at 

I have tested this locally and in ADO. The snippet does exist and when i remove it it fails on the next last record. Prior to upgrade to latest version this worked fine. We download portal content locally and do a commit which deploys the Solution and then execute paportal upload.

Pac cli 1.21.13

**Comment by eugenevanstaden** [comment] 2023-04-13 00:28
@ashishchoudhary001

This issue still occurring and only Uploads successfully when running Download then Upload locally, and not via ADO pipeline. I have enabled Telemetry:
Exception Id: d86d5513-99b2-4e07-9f42-5805e180c215 
Exception Type: System.InvalidCastException

**Comment by MrRishabhJain** [comment] 2023-04-17 12:47
Hi @eugenevanstaden, seems like the issue occurs when the files downloaded by an older version of PAC are uploaded using the latest PAC. As the upload is successful when you locally do a download first, can you try comparing the files before and after the download, and then making those same changes in the files that are being uploaded via the pipelines?

**Comment by MrRishabhJain** [comment] 2023-04-17 12:50
Also, if the above doesn't help, can you share some details on your configurations that would help us replicate the issue on our end, and also the version of the previous PAC cli tool that was working for you. Thanks!

**Comment by eugenevanstaden** [comment] 2023-04-18 01:16
@MrRishabhJain 

I have both the latest locally and in the ADO pipeline, which installs the latest version if CLI per run. I will monitor it as from this morning it seemed to be deploying again correctly.

Would this be the manifest file or the actual Content Snippet files that are older version?

**Comment by eugenevanstaden** [comment] 2023-04-18 02:53
@MrRishabhJain 

I found an issue with Tracking Code in that it creates duplicates as below, 2 with the same content snippet id but different content.

![image](https://user-images.githubusercontent.com/16320095/232658250-318b8d1e-381a-4aad-83a3-c2bae744a0f7.png)

**Comment by eugenevanstaden** [comment] 2023-04-20 05:44
with the latest update: Product Version: 1.22.2+g401780b

Slightly different issue with Upload -both from local and ADO

Object reference not set to an instance of an object.|EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.    at bolt.module.paportal.core.PortalDataManifestProvider..ctor(String webSiteRootPath, AuthProfile currentAuthProfile, ICommandProgress cmdProgress, IOutputWindow ouputWindow, ILogger logger, ILocalizedStrings`1 locale)    at bolt.module.paportal.PortalDataImporter.IterateSchemaAndUploadData(String rootFolderPath)    at bolt.module.paportal.PortalDataImporter.UploadData()    at bolt.module.paportal.verbs.PAPortalUploadVerb.Execute(IContext context, Command command)    at bolt.cli.LegacyVerbExecuteFn.<>c__DisplayClass3_0.<.ctor>b__0(IContext context, Command command, CancellationToken cancellationToken)    at bolt.cli.LegacyVerbExecutor.ExecuteAsync(IContext context, Command command, CancellationToken cancellationToken)    at bolt.cli.Verb.<>c__DisplayClass10_0.<<RunVerbExecutorAsync>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown

**Comment by eugenevanstaden** [comment] 2023-04-26 20:19
@MrRishabhJain

This issue is persisting and i've updated to the latest version of CLI. The scenario is fairly basic in that we download the portal from Development and queue this through to deploy to the next environment, Test, UAT etc. I have deleted the local copy of portal, downloaded again and the error is the same. It fails on the last Content Snippet in the list, which is the Tracking Code with ID: 3cc3637f-0148-ec11-8c62-00224811189e

If I delete this snippet, download and upload to the next environment then it fails again but on the last Snippet in the list again.  

Current version:  1.22.4+gfad5a46 
Was working fine until version 1.21.13

This is the same behaviour when running it locally or via ADO Pipeline. We can do a screen share if that will help in solving this issue?


bolt.module.paportal.PAPortalModule :: ManifestAction: NOT_FOUND detected for entity:adx_contentsnippet id:0a4771ed-1341-ec11-8c62-002248113562 2023-04-26 07:55:03.0302 | INF | bolt.module.paportal.PAPortalModule :: ManifestAction: NOT_FOUND detected for entity:adx_contentsnippet id:3cc3637f-0148-ec11-8c62-00224811189e 2023-04-26 07:55:03.0459 | INF | bolt.cli.CommandProcessor :: EndExecutingVerb (Success: False, Execution Time(ms): 731) 2023-04-26 07:55:03.0928 | FTL | bolt.Session :: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.Object,System.Object]' to type 'System.IConvertible'.|EXCEPTION: System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.Object,System.Object]' to type 'System.IConvertible'.    at System.Convert.ToInt32(Object value, IFormatProvider provider)    at bolt.module.paportal.PAPortalCommon.<>c.<AddAttributeByType>b__4_0(Object x)    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)    at bolt.module.paportal.PAPortalCommon.AddAttributeByType(Dictionary`2 values, String attributeName, Object attributeValue, XmlNode fieldNode)    at bolt.module.paportal.core.PortalDirectoryParser.JsonEntityToDictionary(Dictionary`2 entityData, XmlNode entitySchemaNode, String entityFileName, String entityFolderPath)    at bolt.module.paportal.core.PortalDirectoryParser.ParseEntitySingleFolder(String entityFolderPath, PortalExportImportMetaData metadata, XmlNode entitySchemaNode)    at bolt.module.paportal.core.PortalDirectoryParser.ParseEntityFolder(PortalExportImportMetaData entityMetadata, XmlNode entityXMLNode)    at bolt.module.paportal.PortalDataImporter.IterateSchema(String rootFolderPath, PortalDeploymentConfigProvider portalDeploymentConfigProvider, PortalDataManifestProvider portalManifestProvider, Guid websiteId, XmlNode xn)    at bolt.module.paportal.PortalDataImporter.<>c__DisplayClass30_0.<IterateSchemaAndUploadData>b__1(XmlNode xn)    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>) --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at bolt.module.paportal.PortalDataImporter.IterateSchemaAndUploadData(String rootFolderPath)    at bolt.module.paportal.PortalDataImporter.UploadData()    at bolt.module.paportal.verbs.PAPortalUploadVerb.Execute(IContext context, Command command)    at bolt.cli.LegacyVerbExecuteFn.<>c__DisplayClass3_0.<.ctor>b__0(IContext context, Command command, CancellationToken cancellationToken)    at bolt.cli.LegacyVerbExecutor.ExecuteAsync(IContext context, Command command, CancellationToken cancellationToken)    at bolt.cli.Verb.<>c__DisplayClass10_0.<<RunVerbExecutorAsync>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at bolt.cli.Verb.<RunVerbExecutorAsync>d__10.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at bolt.cli.Verb.<ExecuteWithOutputAsync>d__8.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at bolt.cli.Verb.Execute(IProcessCommandContext context, Command command, Queue`1 nextCommands)    at bolt.cli.CommandProcessor.ProcessCommands(Queue`1 commands, IVerbFactory factory)    at bolt.cli.CommandProcessor.LaunchCommand(IReadOnlyList`1 args, UserHelpText userHelpText, Boolean isNonInteractiveModeEnabled)    at bolt.Session.Run(ProgramArguments args) 2023-04-26 07:55:03.1084 | ERR | bolt.Session ::    at System.Convert.ToInt32(Object value, IFormatProvider provider)    at bolt.module.paportal.PAPortalCommon.<>c.<AddAttributeByType>b__4_0(Object x)    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)    at bolt.module.paportal.PAPortalCommon.AddAttributeByType(Dictionary`2 values, String attributeName, Object attributeValue, XmlNode fieldNode)    at bolt.module.paportal.core.PortalDirectoryParser.JsonEntityToDictionary(Dictionary`2 entityData, XmlNode entitySchemaNode, String entityFileName, String entityFolderPath)    at bolt.module.paportal.core.PortalDirectoryParser.ParseEntitySingleFolder(String entityFolderPath, PortalExportImportMetaData metadata, XmlNode entitySchemaNode)    at bolt.module.paportal.core.PortalDirectoryParser.ParseEntityFolder(PortalExportImportMetaData entityMetadata, XmlNode entityXMLNode)    at bolt.module.paportal.PortalDataImporter.IterateSchema(String rootFolderPath, PortalDeploymentConfigProvider portalDeploymentConfigProvider, PortalDataManifestProvider portalManifestProvider, Guid websiteId, XmlNode xn)    at bolt.module.paportal.PortalDataImporter.<>c__DisplayClass30_0.<IterateSchemaAndUploadData>b__1(XmlNode xn)    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>) --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at bolt.module.paportal.PortalDataImporter.IterateSchemaAndUploadData(String rootFolderPath)    at bolt.module.paportal.PortalDataImporter.UploadData()    at bolt.module.paportal.verbs.PAPortalUploadVerb.Execute(IContext context, Command command)    at bolt.cli.LegacyVerbExecuteFn.<>c__DisplayClass3_0.<.ctor>b__0(IContext context, Command command, CancellationToken cancellationToken)    at bolt.cli.LegacyVerbExecutor.ExecuteAsync(IContext context, Command command, CancellationToken cancellationToken)    at bolt.cli.Verb.<>c__DisplayClass10_0.<<RunVerbExecutorAsync>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at bolt.cli.Verb.<RunVerbExecutorAsync>d__10.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at bolt.cli.Verb.<ExecuteWithOutputAsync>d__8.MoveNext() --- End of stack trace from previous locatio

**Comment by eugenevanstaden** [comment] 2023-05-02 22:46
@MrRishabhJain 

I changed both the Download and Upload by adding the flag --modelVersion 1 

This now uploads successful. As this is not documented on the CLI docs but from this
https://learn.microsoft.com/en-us/power-pages/admin/enhanced-data-model

For now its working, not sure how or why?

**Comment by MrRishabhJain** [comment] 2023-07-26 13:08
Hey @eugenevanstaden, as the issue is now resolved for you, I'm closing this thread. Feel free to re-open or create a new thread in-case you have any further queries.

**Closed by MrRishabhJain** 2023-07-26 13:08 UTC
Labels: paportal
