### ISSUE TITLE
PAC PCF PUSH

### ISSUE THREAD

**Issue by RamNemely** [microsoft/powerplatform-vscode#755] opened 2023-10-27 13:04 UTC
seems that pac pcf push is not working now.

This is the error I am getting when I try to push the changes to connected env,

MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: The switch name extracted from either the partially or completely unquoted arg should be the same.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)
   at Microsoft.Build.CommandLine.MSBuildApp.ExtractSwitchParameters(String commandLineArg, String unquotedCommandLineArg, Int32 doubleQuotesRemovedFromArg, String switchName, Int32 switchParameterIndicator)
   at Microsoft.Build.CommandLine.MSBuildApp.ExtractSwitchParameters(String commandLineArg, String unquotedCommandLineArg, Int32 doubleQuotesRemovedFromArg, String switchName, Int32 switchParameterIndicator)  
   at Microsoft.Build.CommandLine.MSBuildApp.GatherCommandLineSwitches(List`1 commandLineArgs, CommandLineSwitches commandLineSwitches)
   at Microsoft.Build.CommandLine.MSBuildApp.GatherAllSwitches(String commandLine, CommandLineSwitches& switchesFromAutoResponseFile, CommandLineSwitches& switchesNotFromAutoResponseFile)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
[ERROR] Unhandled Exception: Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: The switch name extracted from either the partially or completely unquoted arg should be the same.  
[ERROR]    at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)
[ERROR]    at Microsoft.Build.CommandLine.MSBuildApp.ExtractSwitchParameters(String commandLineArg, String unquotedCommandLineArg, Int32 doubleQuotesRemovedFromArg, String switchName, Int32 switchParameterIndicator)
[ERROR]    at Microsoft.Build.CommandLine.MSBuildApp.GatherCommandLineSwitches(List`1 commandLineArgs, CommandLineSwitches commandLineSwitches)
[ERROR]    at Microsoft.Build.CommandLine.MSBuildApp.GatherAllSwitches(String commandLine, CommandLineSwitches& switchesFromAutoResponseFile, CommandLineSwitches& switchesNotFromAutoResponseFile)[ERROR]    at 
Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
[ERROR]    at Microsoft.Build.CommandLine.MSBuildApp.Main()
Microsoft PowerPlatform CLI
Version: 1.28.3+g4ba7dfd
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions

Thanks
Ram

**Comment by petrochuk** [comment] 2023-10-27 14:53
Closing it as duplicate of https://github.com/microsoft/powerplatform-build-tools/discussions/603

**Closed by petrochuk** 2023-10-27 14:53 UTC
