### ISSUE TITLE
Error: Cannot find module 'vscode'

### ISSUE THREAD

**Issue by danny-su** [microsoft/powerplatform-vscode#946] opened 2024-05-13 12:14 UTC
node:internal/modules/cjs/loader:1087
  throw err;
  ^

Error: Cannot find module 'vscode'
Require stack:
- /Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at Module._load (node:internal/modules/cjs/loader:929:27)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.vscode (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:34497:18)
    at __webpack_require__ (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:43257:42)
    at ./src/common/Utils.ts (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:24372:29)
    at __webpack_require__ (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:43257:42)
    at ./src/common/OneDSLoggerTelemetry/oneDSLoggerWrapper.ts (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:23876:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js'
  ]
}

Node.js v18.18.2
[Info  - 8:12:10 PM] Connection to server got closed. Server will restart.
node:internal/modules/cjs/loader:1087
  throw err;
  ^

Error: Cannot find module 'vscode'
Require stack:
- /Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at Module._load (node:internal/modules/cjs/loader:929:27)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.vscode (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:34497:18)
    at __webpack_require__ (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:43257:42)
    at ./src/common/Utils.ts (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:24372:29)
    at __webpack_require__ (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:43257:42)
    at ./src/common/OneDSLoggerTelemetry/oneDSLoggerWrapper.ts (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:23876:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js'
  ]
}

Node.js v18.18.2
[Info  - 8:12:11 PM] Connection to server got closed. Server will restart.
node:internal/modules/cjs/loader:1087
  throw err;
  ^

Error: Cannot find module 'vscode'
Require stack:
- /Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at Module._load (node:internal/modules/cjs/loader:929:27)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.vscode (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:34497:18)
    at __webpack_require__ (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:43257:42)
    at ./src/common/Utils.ts (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:24372:29)
    at __webpack_require__ (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:43257:42)
    at ./src/common/OneDSLoggerTelemetry/oneDSLoggerWrapper.ts (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:23876:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js'
  ]
}

Node.js v18.18.2
[Info  - 8:12:12 PM] Connection to server got closed. Server will restart.
node:internal/modules/cjs/loader:1087
  throw err;
  ^

Error: Cannot find module 'vscode'
Require stack:
- /Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at Module._load (node:internal/modules/cjs/loader:929:27)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.vscode (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:34497:18)
    at __webpack_require__ (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:43257:42)
    at ./src/common/Utils.ts (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:24372:29)
    at __webpack_require__ (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:43257:42)
    at ./src/common/OneDSLoggerTelemetry/oneDSLoggerWrapper.ts (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:23876:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js'
  ]
}

Node.js v18.18.2
[Info  - 8:12:12 PM] Connection to server got closed. Server will restart.
node:internal/modules/cjs/loader:1087
  throw err;
  ^

Error: Cannot find module 'vscode'
Require stack:
- /Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at Module._load (node:internal/modules/cjs/loader:929:27)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.vscode (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:34497:18)
    at __webpack_require__ (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:43257:42)
    at ./src/common/Utils.ts (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:24372:29)
    at __webpack_require__ (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:43257:42)
    at ./src/common/OneDSLoggerTelemetry/oneDSLoggerWrapper.ts (/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js:23876:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/danny/.vscode/extensions/microsoft-isvexptools.powerplatform-vscode-2.0.49/dist/yamlServer.js'
  ]
}

Node.js v18.18.2
[Error - 8:12:12 PM] Connection to server got closed. Server will not be restarted.

**Comment by tyaginidhi** [comment] 2024-07-04 09:46
Duplicate of https://github.com/microsoft/powerplatform-vscode/issues/893

**Closed by tyaginidhi** 2024-07-04 09:46 UTC
