### ISSUE TITLE
Nothing happen after click on "Add Auth Profile"?

### ISSUE THREAD

**Issue by KwernHe** [microsoft/powerplatform-vscode#276] opened 2022-08-24 12:27 UTC
After the extension(Power Platform Tools) get installed on my VSCode, when I tried to click on "Add Auth Profile" to sign it, but nothing happens? Anyone can please help on this? 

<img width="380" alt="Screen Shot 2022-08-24 at 20 27 08" src="https://user-images.githubusercontent.com/23133322/186418138-5e981931-1e72-4448-9b38-3a99793b61dd.png">
?

**Comment by rayzorben** [comment] 2022-08-30 20:04
I had the same issue, but it really was just opening an authentication window behind vscode that I had to find and authenticate with.

**Comment by tehcrashxor** [comment] 2022-08-30 21:13
There could be a couple things going on here.   The authentication process launches a dialog (Windows) or your browser (Mac & Linux), which often launches behind the current window as @rayzorben said above.

This same symptom appears when the prerequisite .NET 6.0 is not installed on the machine.  If your Mac is an Apple Silicon M1/M2, you will need to install _both_ the x64 and arm64 versions of .NET6.0 as noted in the 1.0.20 release notes.

@KwernHe , if neither of those is the case, please check that running `pac` in a VS Code terminal successfully executes.  If so, can you successfully authenticate via `pac auth create`?

**Comment by ronram5126** [comment] 2022-09-24 09:12
I had same issue. Resolved by reinstalling all dotnet-* packages and this extension...

**Comment by anastaciaeg** [comment] 2023-02-17 19:14
Since uninstalling the extension and all dotnet packages on a new Apple M1 computer did not resolve this issue for me, I'm going to document the process I used to fix my install.  Though it's not likely to be something others can reproduce, it may at least help with narrowing down the problem.

First, I uninstalled the extension in an effort to "start over."

Next, following steps provided [here](https://maartenmerken.medium.com/installing-net-6-alpha-on-your-m1-mac-23a35aa6f02c), I used [this script](https://github.com/dotnet/cli/blob/master/scripts/obtain/uninstall/dotnet-uninstall-pkgs.sh) to uninstall my previous installations of dotnet.

Using [this issue](https://github.com/microsoft/powerplatform-vscode/issues/139#issuecomment-988327820) as a starting place, I then reinstalled both the arm64 and x64 versions of dotnet to my system. I used a terminal session to browse my dotnet installation and confirm that both versions appeared as expected.  
```bash
which dotnet
ls /usr/local/share/dotnet/
```

I then reinstalled the Power Platforms Tools extension in VS Code.

At this point, I couldn't continue with that recommended solution because I still was receiving a "pac command not found" error in all terminal windows after restart (which was my original issue and the reason I was researching the Add Auth Profile problem to begin with).  

I browsed in terminal to the tools extension in my user library:
```bash
cd ~/Library/Application\ Support/Code/User/globalStorage/microsoft-isvexptools.powerplatform-vscode/pac/tools
```

There I eventually identified that the pac executable was not getting installed on my system.  (I have no idea why!) Luckily, I had a backup from a previous system that I was able to grab the old extension install and copy it to my new system.
```bash
cp -rf PATH_TO_BACKUP/Library/Application\ Support/Code/User/globalStorage/microsoft-isvexptools.powerplatform-vscode/pac ~/Library/Application\ Support/Code/User/globalStorage/microsoft-isvexptools.powerplatform-vscode/pac
```

I then inspected my $PATH to determine which was the best location to make a symlink for the pac executable.
```
echo $PATH

# I chose ~/.dotnet/tools from my $PATH as a good place to put the symlink and created it using...
ln -s ~/Library/Application\ Support/Code/User/globalStorage/microsoft-isvexptools.powerplatform-vscode/pac ~/.dotnet/tools/pac
```

Finally, I restarted Code and tested everything, and I was back up and running.  I successfully added an Auth Profile via Code and browser and then was once again able to execute pac commands in terminal.

The key here is that the pac executable wasn't getting installed for some reason and I was only able to resolve the issue because I had a copy of it elsewhere, allowing me to manually install it.

**Closed** 2023-08-05 14:11 UTC
Labels: Need more Info
