### ISSUE TITLE
Client Secret Error

### ISSUE THREAD

**Issue by SimonCrelling-S-RM** [microsoft/powerplatform-vscode#456] opened 2023-02-21 10:34 UTC
Hi,

I create auth profiles using an Application User and App Registration in Azure (`pac auth create`). Every day I have to delete and recreate the profiles due to the error below.  I use the same credentials (client secret) every time, and the connection works for the day when I create it.

Error: Failed to connect to Dataverse
    Failed to connect to Dataverse
        One or more errors occurred.
            ExternalTokenManagement Authentication Requested but not configured correctly. 003
                A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app <APPID>

**Comment by sanjeev40084** [comment] 2023-02-23 21:08
@SimonCrelling-S-RM i was running into this issue too and like you i have been clearing and creating auth profile everyday while working on this issue: #393 I thought i was doing something wrong but looks like i was not the only one. would love to see if there is better solution than need to do this everytime when we run the pac command.

**Comment by sanjeev40084** [comment] 2023-02-23 21:20
looks like this might be workaround, haven't tested it though: check out @davidjenni response in this issue #297

**Comment by tehcrashxor** [comment] 2023-03-04 00:08
Duplicate of #297

**Closed by tehcrashxor** 2023-03-04 00:08 UTC
Labels: duplicate, known issue
