### ISSUE TITLE
PowerApps Html Language Server Crashed Error

### ISSUE THREAD

**Issue by daryllabar** [microsoft/powerplatform-vscode#916] opened 2024-04-25 18:27 UTC
I keep on getting this error when loading VSCode:
![image](https://github.com/microsoft/powerplatform-build-tools/assets/9728423/e4e473dd-0209-4a64-bc1f-e18e1c9f2b04)

**Comment by nsearle97** [comment] 2024-04-29 12:59
I'm getting the same error. Was working absolutely fine a few days ago, now I can't seem to connect to power apps and I get this error whenever I load VS Code. I can list the portals in the environment, but it fails to download one saying "this portal does not exist", despite it showing in the "list" results.

**Comment by MKUltraCSA** [comment] 2024-05-10 14:28
Also running into this error. anyone find a resolution yet?

**Comment by pdavisbdbc** [comment] 2024-05-10 15:29
I can confirm I am also running into this error. Here is more information from the logs:
2024-05-10 11:24:27.995 [info] ExtensionService#_doActivateExtension vscode.html-language-features, startup: false, activationEvent: 'onLanguage:html'
2024-05-10 11:24:33.181 [error] Error: Connection to server got closed. Server will not be restarted.
	at LanguageClient.handleConnectionClosed (c:\Users\PED\.vscode\extensions\microsoft-isvexptools.powerplatform-vscode-2.0.49\dist\extension.js:76637:47)
	at LanguageClient.handleConnectionClosed (c:\Users\PED\.vscode\extensions\microsoft-isvexptools.powerplatform-vscode-2.0.49\dist\extension.js:80489:15)
	at closeHandler (c:\Users\PED\.vscode\extensions\microsoft-isvexptools.powerplatform-vscode-2.0.49\dist\extension.js:76606:18)
	at CallbackList.invoke (c:\Users\PED\.vscode\extensions\microsoft-isvexptools.powerplatform-vscode-2.0.49\dist\extension.js:72205:39)
	at Emitter.fire (c:\Users\PED\.vscode\extensions\microsoft-isvexptools.powerplatform-vscode-2.0.49\dist\extension.js:72267:36)
	at closeHandler (c:\Users\PED\.vscode\extensions\microsoft-isvexptools.powerplatform-vscode-2.0.49\dist\extension.js:71281:26)
	at CallbackList.invoke (c:\Users\PED\.vscode\extensions\microsoft-isvexptools.powerplatform-vscode-2.0.49\dist\extension.js:72205:39)
	at Emitter.fire (c:\Users\PED\.vscode\extensions\microsoft-isvexptools.powerplatform-vscode-2.0.49\dist\extension.js:72267:36)
	at IPCMessageReader.fireClose (c:\Users\PED\.vscode\extensions\microsoft-isvexptools.powerplatform-vscode-2.0.49\dist\extension.js:72951:27)
	at ChildProcess.<anonymous> (c:\Users\PED\.vscode\extensions\microsoft-isvexptools.powerplatform-vscode-2.0.49\dist\extension.js:73679:45)
	at ChildProcess.emit (node:events:529:35)
	at ChildProcess.emit (node:domain:489:12)
	at maybeClose (node:internal/child_process:1098:16)
	at ChildProcess._handle.onexit (node:internal/child_process:303:5)

**Comment by pdavisbdbc** [comment] 2024-05-10 15:50
I apologize for the additional comment. The logs from the PowerApps Html Language Server output might be more useful. Attached.
[PowerApps Html Language Server Log](https://github.com/microsoft/powerplatform-vscode/files/15277055/PowerApps.Html.Language.Server.Log)

**Comment by tyaginidhi** [comment] 2024-07-04 09:47
Duplicate of https://github.com/microsoft/powerplatform-vscode/issues/893

**Closed by tyaginidhi** 2024-07-04 09:47 UTC
