### ISSUE TITLE
Extension does not work inside DevContainers

### ISSUE THREAD

**Issue by rajyraman** [microsoft/powerplatform-vscode#51] opened 2021-05-27 23:41 UTC
I can install the extension inside a DevContainer with javascript-node:16-buster image, but I cannot run pac inside the bash. I tried with 12-buster - same issue.

![image](https://user-images.githubusercontent.com/5035266/119909613-a2ab4680-bf98-11eb-8e6f-8697097cac93.png)

**Comment by rajyraman** [comment] 2021-05-28 00:06
I did some digging around. The nupkg files exist but it has not been extracted into globalStorage

![image](https://user-images.githubusercontent.com/5035266/119911042-ebb0ca00-bf9b-11eb-8d2c-6d5c86a051ef.png)

Compare this with Windows.

![image](https://user-images.githubusercontent.com/5035266/119911235-41857200-bf9c-11eb-8304-369134b56087.png)

**Comment by davidjenni** [comment] 2021-06-04 01:02
@rajyraman yes, this is currently by design: the only 2 OS supported for now are Windows and macOS; you're running in a Linux subsystem which this extension does not support yet. We're working on enabling both running in WSL on Windows and on a full linux w/ window manager/GUI VSCode.
It's not a secret that we have a linux version of the pac CLI, we have GitHub Actions running with both Win and linux runner OS. That support has not been tagged yet as @v0 or @latest but is available as HEAD or by commit id for the adventurous for now...

**Comment by davidjenni** [comment] 2021-06-04 01:03
closing for now, as WSL and linux are planned feature work for later. In the meantime, please use the extension in VSCode on Win (no WSL or DevContainers) and macOS only

**Closed by davidjenni** 2021-06-04 01:03 UTC
Labels: enhancement
